const fs = require('fs');
const path = require('path');
const basePath = 'C:\\Users\\Seonkyu\\special-chars\\en';

// Tool-specific Korean→English mapping
const toolTranslations = {
  'char-counter': [
    ['📏 글자 수 계산기 — 티모집사', '📏 Character Counter — TeemoZipsa'],
    ['📏 글자 수 계산기', '📏 Character Counter'],
    ['글자 수, 단어 수, 바이트 수를 실시간으로 세어주는 글자 수 계산기입니다.', 'Count characters, words, and bytes in real time.'],
    ['글자 수, 단어 수, 바이트 수를 실시간으로 세어줍니다.', 'Count characters, words, and bytes in real time.'],
    ['글자수 세기', 'Character Counter'],
    ['공백 포함', 'With spaces'],
    ['공백 제외', 'Without spaces'],
    ['단어 수', 'Words'],
    ['줄 수', 'Lines'],
    ['바이트 수', 'Bytes'],
    ['여기에 텍스트를 입력하세요...', 'Type or paste your text here...'],
    ['여기에 텍스트를 입력하거나 붙여넣으세요', 'Type or paste your text here'],
    ['텍스트를 입력하세요', 'Enter text here'],
    ['글자수 계산기', 'Character Counter'],
    ['글자', 'Characters'],
    ['단어', 'Words'],
    ['문장', 'Sentences'],
    ['문단', 'Paragraphs'],
    ['읽기 시간', 'Reading time'],
    ['발표 시간', 'Speech time'],
    ['분', 'min'],
    ['초', 'sec'],
    ['트위터', 'Twitter'],
    ['인스타그램', 'Instagram'],
    ['입력한 텍스트가 없습니다', 'No text entered'],
    ['내용을 지우시겠습니까?', 'Clear all text?'],
    ['지우기', 'Clear'],
    ['실시간 글자수 카운터', 'Real-time Character Counter'],
  ],
  'speech-timer': [
    ['🎤 발표시간 계산기 — 티모집사', '🎤 Speech Timer — TeemoZipsa'],
    ['🎤 발표시간 계산기', '🎤 Speech Timer'],
    ['발표 원고를 붙여넣으면 예상 소요 시간을 계산합니다', 'Paste your speech script to estimate presentation time'],
    ['발표 원고를 붙여넣으면 예상 소요 시간을 계산합니다.', 'Paste your speech script to estimate presentation time.'],
    ['발표 원고를 입력하세요...', 'Paste your speech script here...'],
    ['여기에 발표 원고를 붙여넣으세요', 'Paste your speech script here'],
    ['발표 속도', 'Speaking speed'],
    ['느리게', 'Slow'],
    ['보통', 'Normal'],
    ['빠르게', 'Fast'],
    ['예상 발표 시간', 'Estimated speech time'],
    ['총 글자수', 'Total characters'],
    ['총 단어수', 'Total words'],
    ['분당 글자수', 'Characters/min'],
    ['슬라이드 수 (선택)', 'Number of slides (optional)'],
    ['슬라이드당 시간', 'Time per slide'],
    ['분/슬라이드', 'min/slide'],
    ['슬라이드 전환 시간 포함', 'Including slide transitions'],
    ['발표시간 계산기', 'Speech Timer'],
    ['예상 소요 시간', 'Estimated time'],
    ['약', 'approx.'],
  ],
  'emoji-mixer': [
    ['🎨 이모지 믹서 — 티모집사', '🎨 Emoji Mixer — TeemoZipsa'],
    ['🎨 이모지 믹서', '🎨 Emoji Mixer'],
    ['두 이모지를 조합해 새로운 이모지를 만들어보세요', 'Combine two emojis to create something new'],
    ['두 이모지를 선택하면 구글 이모지 키친에서 조합된 결과를 보여줍니다.', 'Select two emojis and see the combined result from Google Emoji Kitchen.'],
    ['이모지를 선택하세요', 'Select an emoji'],
    ['이모지 1', 'Emoji 1'],
    ['이모지 2', 'Emoji 2'],
    ['조합 결과', 'Result'],
    ['랜덤 조합', 'Random Mix'],
    ['이미지 저장', 'Save Image'],
    ['링크 복사', 'Copy Link'],
    ['조합된 결과가 없습니다', 'No combination found'],
    ['이모지를 선택해주세요', 'Please select an emoji'],
    ['검색...', 'Search...'],
    ['이모지 검색', 'Search emojis'],
    ['인기', 'Popular'],
    ['스마일', 'Smileys'],
    ['동물', 'Animals'],
    ['음식', 'Food'],
    ['활동', 'Activities'],
    ['여행', 'Travel'],
    ['사물', 'Objects'],
    ['기호', 'Symbols'],
    ['최근 사용', 'Recent'],
    ['이모지 조합기', 'Emoji Combiner'],
    ['복사됨!', 'Copied!'],
    ['저장됨!', 'Saved!'],
    ['링크가 복사되었습니다', 'Link copied to clipboard'],
  ],
  'zodiac-calc': [
    ['⭐ 별자리 계산기 — 티모집사', '⭐ Zodiac Calculator — TeemoZipsa'],
    ['⭐ 별자리 계산기', '⭐ Zodiac Calculator'],
    ['생년월일로 별자리, 탄생석, 탄생화를 알아보세요.', 'Find your zodiac sign, birthstone, and birth flower by your birthday.'],
    ['생년월일을 입력하세요', 'Enter your birthday'],
    ['생년월일', 'Date of Birth'],
    ['년', 'Year'],
    ['월', 'Month'],
    ['일', 'Day'],
    ['알아보기', 'Find Out'],
    ['별자리', 'Zodiac Sign'],
    ['탄생석', 'Birthstone'],
    ['탄생화', 'Birth Flower'],
    ['성격 특성', 'Personality'],
    ['궁합', 'Compatibility'],
    ['최고의 궁합', 'Best Match'],
    ['좋은 궁합', 'Good Match'],
    ['행운의 숫자', 'Lucky Number'],
    ['행운의 색', 'Lucky Color'],
    ['별자리 찾기', 'Zodiac Finder'],
    ['양자리', 'Aries'], ['황소자리', 'Taurus'], ['쌍둥이자리', 'Gemini'],
    ['게자리', 'Cancer'], ['사자자리', 'Leo'], ['처녀자리', 'Virgo'],
    ['천칭자리', 'Libra'], ['전갈자리', 'Scorpio'], ['사수자리', 'Sagittarius'],
    ['염소자리', 'Capricorn'], ['물병자리', 'Aquarius'], ['물고기자리', 'Pisces'],
    ['가넷', 'Garnet'], ['자수정', 'Amethyst'], ['아쿠아마린', 'Aquamarine'],
    ['다이아몬드', 'Diamond'], ['에메랄드', 'Emerald'], ['진주', 'Pearl'],
    ['루비', 'Ruby'], ['페리도트', 'Peridot'], ['사파이어', 'Sapphire'],
    ['오팔', 'Opal'], ['토파즈', 'Topaz'], ['터키석', 'Turquoise'],
    ['카네이션', 'Carnation'], ['제비꽃', 'Violet'], ['수선화', 'Daffodil'],
    ['데이지', 'Daisy'], ['은방울꽃', 'Lily of the Valley'], ['장미', 'Rose'],
    ['수국', 'Larkspur'], ['글라디올러스', 'Gladiolus'], ['아스터', 'Aster'],
    ['금잔화', 'Marigold'], ['국화', 'Chrysanthemum'], ['포인세티아', 'Poinsettia'],
  ],
  'prompt-gen': [
    ['🤖 AI 프롬프트 생성기 — 티모집사', '🤖 AI Prompt Generator — TeemoZipsa'],
    ['🤖 AI 프롬프트 생성기', '🤖 AI Prompt Generator'],
    ['AI 프롬프트를 쉽고 빠르게 생성하세요', 'Generate effective AI prompts easily'],
    ['원하는 작업을 선택하고 세부 정보를 입력하면 최적의 프롬프트가 생성됩니다.', 'Select a task and fill in details to generate the optimal prompt.'],
    ['작업 유형', 'Task Type'],
    ['글쓰기', 'Writing'],
    ['번역', 'Translation'],
    ['요약', 'Summary'],
    ['코딩', 'Coding'],
    ['마케팅', 'Marketing'],
    ['분석', 'Analysis'],
    ['교육', 'Education'],
    ['창작', 'Creative'],
    ['주제/내용', 'Topic/Content'],
    ['예: 블로그 포스트 주제, 번역할 텍스트 등', 'e.g. blog post topic, text to translate, etc.'],
    ['톤/스타일', 'Tone/Style'],
    ['전문적', 'Professional'],
    ['친근한', 'Friendly'],
    ['격식체', 'Formal'],
    ['캐주얼', 'Casual'],
    ['유머러스', 'Humorous'],
    ['대상', 'Target Audience'],
    ['일반', 'General'],
    ['전문가', 'Expert'],
    ['학생', 'Student'],
    ['어린이', 'Children'],
    ['비즈니스', 'Business'],
    ['추가 요구사항', 'Additional Requirements'],
    ['길이, 형식, 특별 지시 등', 'Length, format, special instructions, etc.'],
    ['프롬프트 생성', 'Generate Prompt'],
    ['생성된 프롬프트', 'Generated Prompt'],
    ['프롬프트 복사', 'Copy Prompt'],
    ['프롬프트가 복사되었습니다!', 'Prompt copied to clipboard!'],
    ['AI 프롬프트 생성기', 'AI Prompt Generator'],
    ['다시 생성', 'Regenerate'],
  ],
  'utm-builder': [
    ['🔗 UTM 빌더 — 티모집사', '🔗 UTM Builder — TeemoZipsa'],
    ['🔗 UTM 빌더', '🔗 UTM Builder'],
    ['UTM 파라미터가 포함된 추적 URL을 쉽게 생성합니다.', 'Easily create tracking URLs with UTM parameters.'],
    ['UTM 파라미터가 포함된 URL을 쉽게 생성하세요', 'Easily create URLs with UTM parameters'],
    ['웹사이트 URL', 'Website URL'],
    ['필수', 'Required'],
    ['선택', 'Optional'],
    ['캠페인 소스', 'Campaign Source'],
    ['캠페인 매체', 'Campaign Medium'],
    ['캠페인 이름', 'Campaign Name'],
    ['캠페인 용어', 'Campaign Term'],
    ['캠페인 콘텐츠', 'Campaign Content'],
    ['생성된 URL', 'Generated URL'],
    ['URL 복사', 'Copy URL'],
    ['URL이 복사되었습니다', 'URL copied to clipboard'],
    ['단축 URL', 'Short URL'],
    ['QR코드 생성', 'Generate QR Code'],
    ['미리보기', 'Preview'],
    ['히스토리', 'History'],
    ['예: google, naver, instagram', 'e.g. google, facebook, instagram'],
    ['예: cpc, email, social, banner', 'e.g. cpc, email, social, banner'],
    ['예: spring_sale, product_launch', 'e.g. spring_sale, product_launch'],
    ['예: running+shoes', 'e.g. running+shoes'],
    ['예: banner_v2, text_link', 'e.g. banner_v2, text_link'],
    ['UTM 추적 URL 생성기', 'UTM Tracking URL Builder'],
  ],
  'pet-age-calc': [
    ['🐾 반려동물 나이 계산기 — 티모집사', '🐾 Pet Age Calculator — TeemoZipsa'],
    ['🐾 반려동물 나이 계산기', '🐾 Pet Age Calculator'],
    ['반려동물의 사람 나이를 계산해보세요.', 'Calculate your pet\'s age in human years.'],
    ['반려동물의 나이를 사람 나이로 환산합니다.', 'Convert your pet\'s age to human years.'],
    ['반려동물 종류', 'Pet Type'],
    ['강아지', 'Dog'],
    ['고양이', 'Cat'],
    ['소형견', 'Small Dog'],
    ['중형견', 'Medium Dog'],
    ['대형견', 'Large Dog'],
    ['초대형견', 'Giant Dog'],
    ['반려동물 나이', 'Pet Age'],
    ['사람 나이로', 'In Human Years'],
    ['살', 'years old'],
    ['나이를 입력하세요', 'Enter age'],
    ['나이 단계', 'Life Stage'],
    ['아기', 'Baby'],
    ['유아', 'Toddler'],
    ['청소년', 'Teenager'],
    ['청년', 'Young Adult'],
    ['성인', 'Adult'],
    ['중년', 'Middle-aged'],
    ['시니어', 'Senior'],
    ['노년', 'Elderly'],
    ['품종별 평균 수명', 'Average Lifespan by Breed'],
    ['반려동물 나이 환산기', 'Pet Age Converter'],
    ['개월', 'months'],
  ],
  'pet-food-calc': [
    ['🍖 반려동물 사료 계산기 — 티모집사', '🍖 Pet Food Calculator — TeemoZipsa'],
    ['🍖 반려동물 사료 계산기', '🍖 Pet Food Calculator'],
    ['반려동물에게 맞는 일일 사료 급여량을 계산합니다.', 'Calculate the right daily food portion for your pet.'],
    ['반려동물 종류', 'Pet Type'],
    ['강아지', 'Dog'],
    ['고양이', 'Cat'],
    ['체중', 'Weight'],
    ['kg', 'kg'],
    ['활동량', 'Activity Level'],
    ['적음', 'Low'],
    ['보통', 'Normal'],
    ['많음', 'High'],
    ['매우 많음', 'Very High'],
    ['나이', 'Age'],
    ['퍼피/키튼', 'Puppy/Kitten'],
    ['성견/성묘', 'Adult'],
    ['노견/노묘', 'Senior'],
    ['중성화 여부', 'Neutered/Spayed'],
    ['했음', 'Yes'],
    ['안했음', 'No'],
    ['일일 권장 급여량', 'Daily Recommended Portion'],
    ['칼로리', 'Calories'],
    ['건사료', 'Dry food'],
    ['습식사료', 'Wet food'],
    ['급여 횟수', 'Meals per day'],
    ['회', 'times'],
    ['1회 급여량', 'Per meal'],
    ['사료 급여 가이드', 'Feeding Guide'],
    ['품종 검색', 'Search breeds'],
    ['사료 계산기', 'Food Calculator'],
  ],
  'pet-bmi-calc': [
    ['⚖️ 반려동물 체중 관리 — 티모집사', '⚖️ Pet Weight Manager — TeemoZipsa'],
    ['⚖️ 반려동물 체중 관리', '⚖️ Pet Weight Manager'],
    ['반려동물의 체중 관리와 BCS를 확인합니다.', 'Monitor your pet\'s weight and body condition score (BCS).'],
    ['반려동물의 건강한 체중을 관리하세요.', 'Keep your pet at a healthy weight.'],
    ['반려동물 종류', 'Pet Type'],
    ['강아지', 'Dog'],
    ['고양이', 'Cat'],
    ['품종', 'Breed'],
    ['품종 검색', 'Search breeds'],
    ['현재 체중', 'Current Weight'],
    ['체형 점수 (BCS)', 'Body Condition Score (BCS)'],
    ['매우 마름', 'Very Thin'],
    ['마름', 'Thin'],
    ['정상', 'Normal'],
    ['과체중', 'Overweight'],
    ['비만', 'Obese'],
    ['이상적인 체중', 'Ideal Weight'],
    ['체중 상태', 'Weight Status'],
    ['적정 체중입니다', 'Healthy weight'],
    ['체중 감량이 필요합니다', 'Weight loss needed'],
    ['체중 증가가 필요합니다', 'Weight gain needed'],
    ['체중 관리 팁', 'Weight Management Tips'],
    ['반려동물 체중 관리', 'Pet Weight Manager'],
  ],
};

for (const [tool, translations] of Object.entries(toolTranslations)) {
  const filePath = path.join(basePath, tool, 'index.html');
  let content = fs.readFileSync(filePath, 'utf8');
  
  for (const [ko, en] of translations) {
    content = content.split(ko).join(en);
  }
  
  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`Translated: ${tool} (${translations.length} replacements)`);
}

console.log('\nAll tool-specific translations applied!');
